// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gagevnmjoooaypruysnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhZ2V2bm1qb29vYXlwcnV5c25jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTE4ODYsImV4cCI6MjA2OTk2Nzg4Nn0.5B1vJCTj-JdmFKH73YxcooZwSmjYwfXcLP4pxl-c8r0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});